services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/certs
    ports:
      - "3001:5173"
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_REMEMBER=${EMAIL_REMEMBER}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWTS=${JWTS}

  prod:
    build:
      context: .
      target: prod
    volumes:
      - ./certs:/certs
    ports:
      - "3001:3001"
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_REMEMBER=${EMAIL_REMEMBER}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWTS=${JWTS}